### PR TITLE
Release/0.6.0

### PR DESCRIPTION
**Pull request by matschaffer**
Updates to prep for 0.6.0 release

## Tests that need verification or removal

- [x] @matschaffer - amazon_linux_2016_03_bootstrap_test.rb - updated
- [x] @matschaffer - archlinux_20131128_test.rb - removed
- [x] @matschaffer - centos6_3_test.rb - bug fixed (a4e3906), might fix other tests too
- [x] @matschaffer - centos7_test.rb - passed
- [x] @matschaffer - debian7_knife_bootstrap_test.rb - bug fixed (f63e69f)
- [x] @matschaffer - gentoo2011_test.rb - removed
- [x] @matschaffer - omnios_r151004_test.rb - updated (82f5480)
- [x] @matschaffer - scientific_linux_63_test.rb - passed
- [x] @matschaffer - sles_11_test.rb - passed
- [x] @matschaffer - ubuntu12_04_bootstrap_test.rb - passed
- [x] @matschaffer - ubuntu12_04_ohai_hints_test.rb - passed
- [x] @matschaffer - ubuntu12_04_test.rb - passed

## Final steps
- [x] fix unit tests
- [x] rebase on master
- [x] run full integration
- [x] update changelog

### CODE REVIEW

**Comment by matschaffer** [comment]
Looks like I may need to roll back #468 since even the integration suite ends up with file names too long. Also considering switching the control socket default to "no" which would call for a rollback of #453.

**Comment by matschaffer** [comment]
Integration suite is partially passing with shorter control paths. Will have to investigate the failed cases.

**Comment by ravenbyron** [comment]
any updates on this blocked on upgrading my chef because
 https://github.com/matschaffer/knife-solo/issues/478 
Thanks

**Comment by matschaffer** [comment]
@ravenbyron still working through the integration suite. I just pushed a CentOS 7 test that should work but doesn't. I've confirmed `amazon_linux_2016_03_bootstrap_test.rb` and `centos6_3_test.rb` as working so far. Pretty sure ubuntu was good too, but I'm just going to work down the list.

**Comment by aried3r** [comment]
Any way we can help? :)

**Comment by matschaffer** [comment]
@aried3r the integration suite needs to get fixed one way or another. https://github.com/matschaffer/knife-solo/blob/master/script/newb has some setup steps & instructions if you want to help out with running them and getting them to pass.

I'd recommend running each one individually (e.g., `ruby -Itest test/integration/debian7_knife_bootstrap_test.rb`) at this stage.

If you run the whole suite it'll leave all the instances running regardless of pass/fail and rack up a bit of an AWS bill. If you just run one and it passes it'll terminate and you can move on to the next one.

I'll start a check list in the description of this PR so we at least can keep track of what has been addressed.

**Comment by matschaffer** [comment]
@aried3r I've added you as a collaborator which should allow you to make updates to the description. Maybe plan to add your name in front of a test before you start working on it so we don't duplicate effort.

**Comment by aried3r** [comment]
Thanks! I do not yet have an AWS account, can I run the tests with a Free-Tier account?

**Comment by matschaffer** [comment]
@aried3r no idea. My AWS account is too old to qualify. I usually plan on $20-$50/mo when working on this stuff.

**Comment by matschaffer** [comment]
The integrations were all written pre-docker. At some point I'd love to swap out all the linux tests to use docker containers instead. Should be able to save a lot of time and money that way.

**Comment by matschaffer** [comment]
The test suite could use an overhaul in general honestly. The whole `ruby -Itest` thing stems back to 2011. ;)

Should really just use rspec at this point.

**Comment by aried3r** [comment]
I guess using docker, one could run these locally?

**Comment by matschaffer** [comment]
With any docker host. Docker-machine for local work for example. Though I can't say for sure if there are good base images for various distros or not.

**Comment by matschaffer** [comment]
Guess that's one bonus to EC2. It's a wealth of old OS images since AMIs seem to rarely go away.

**Comment by matschaffer** [comment]
Okay, folks. Just pushed 0.6.0 to https://rubygems.org/gems/knife-solo

Let me know if you run into any trouble and we can release a .1 if needed.

**Comment by jeroenj** [comment]
Awesome! Good stuff. Will try it out tonight. 👍

**Comment by aried3r** [comment]
Thank you for your work! I'll try it out right now.

**Comment by aried3r** [comment]
Just set up a new machine using 0.6.0, worked as expected. :)

**Comment by jeroenj** [comment]
I can also confirm that it works as expected! :)

**Pull request merged**
