### PR TITLE
Enabled local_mode in solo.rb.erb

### PR DESCRIPTION
**Pull request by runningman84**
PR for #353

### CODE REVIEW

**Comment by florian-asche** [comment]
still missing

**Comment by rmoriz** [comment]
I'm not sure if chef-zero works as expected. AFAIK it is incompatible wich chef-solo-search and will crash chef-zero (chef-solo local mode) converges, at least this is what I'm run into when using test-kitchen with chef-zero if a cookbook dependency injects chef-solo-search (which knife-solo afaik does by default when uploading the cookbooks).
https://github.com/pspdfkit-ops/chef-solo-search/commit/02ff543f09915a497e0c2c1a5e7dbf63af9e2620

**Comment by florian-asche** [comment]
If you provide some basic steps to test it (how/what files to change) then i can test tomorrow if search is working as expected.

**Comment by matschaffer** [comment]
If nothing else, chef zero requires that roles & environment files be json rather than ruby. That's something I'd like to get ironed out (e.g., have a pre-processing step that does the conversion) before supporting local mode from knife-solo.

We also need to add logic to remove the search cookbook when running local mode.

**Comment by matschaffer** [comment]
Oh, and there's the question of what to do about node writes. When running in local mode do we want to copy the resulting node files back to the client?

If not people might be surprised when their node attributes are not saved or subsequent runs.

**Comment by runningman84** [comment]
@matschaffer wrting results back sounds like a good idea.

If you publish the feature without that function I want not complain either. I would really like to see local mode included soon because we monkey patch knife-solo right now which is not very user friendly.

We have a lot of cookbooks who look like this:
```
# search for all items in the 'components' data bag and loop over them
search(:components, "cookbook:myapache AND hostname:#{hostname}") do |component|
  fail 'missing id' unless component['id']

end
```
They work just fine, we do not see any crashes maybe because we do not include chef-solo-search.

**Comment by rmoriz** [comment]
knife-zero for example writes back all node attributes which is nice but also some kind of over-verbose (all ohai attributes…lots of changes on each converge )

**Comment by rmoriz** [comment]
@florian-asche just create a blank cookbook with a dependency to 'chef-solo-search' in its metadata. then try to converge it using chef-zero (e.g. using test-kitchen). Due to the file structure of chef-solo-search the "upload" to the in-memory chef-server will fail (or some parts of the cookbook will be missing).

**Comment by matschaffer** [comment]
@rmoriz ouch. Perhaps the initial implementation shouldn't worry about getting node data back to the client then.

Wonder if there's something we could do to at least ensure the file on the host doesn't get clobbered so it can be used on the next run.

**Comment by rmoriz** [comment]
@matschaffer chef-client can white-list/black-list attributes it sends back to chef-server (chef-zero). `automatic_attribute_whitelist ` in https://docs.chef.io/config_rb_client.html

**Comment by matschaffer** [comment]
Not really. I can't merge as is since I pretty sure it'll break anyone not already using json roles & environments, potentially other issues too. 

I'm all for chef zero but it'll have to be a more concerted effort.

**Pull request closed without merging**
